### PR TITLE
Added triangle + usage in linux

### PR DESCRIPTION
**Pull request by proh14**
Hello, this is the code for the issue can you please add the hacktoberfest-accepted tag to this pr?
and if you saw any problems contact me (like Linux not working etc)

### CODE REVIEW

**Comment by blueberry077** [comment]
I thought you added [Bresenham's line algorithm](https://en.wikipedia.org/wiki/Bresenham%27s_line_algorithm)
in order to draw lines and triangles.

**Comment by proh14** [comment]
hello
does this get the work done?

``` C
void draw_line(struct Canvas c, size_t x1, size_t y1, size_t x2, size_t y2, int t) {
    int dx = abs((int)x2 - (int)x1);
    int sx = x1 < x2 ? 1 : -1;
    int dy = -abs((int)y2 - (int)y1);
    int sy = y1 < y2 ? 1 : -1;
    int err = dx + dy;
    int e2;

    while (1) {
        set_pixel(c, x1, y1, t);

        if (x1 == x2 && y1 == y2) {
            break;
        }

        e2 = 2 * err;
        if (e2 >= dy) {
            err += dy;
            x1 += sx;
        }
        if (e2 <= dx) {
            err += dx;
            y1 += sy;
        }
    }
}
`````

**Comment by blueberry077** [comment]
thank you it work very well :D
image
```c
/* Include Standard Libraries */
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <windows.h>
#include "include/term_canvas.h"
/* Entry Point .............. */
int main(void)
{
	struct Canvas canvas = new_canvas(120, 104);
	set_terminal_mode();
	draw_line(canvas, 20, 80, 32, 32, 1);
	draw_line(canvas, 32, 32, 70, 40, 1);
	draw_line(canvas, 70, 40, 20, 80, 1);
	draw_canvas(canvas);
	free_canvas(canvas);
	return 0;
}
/* .......................... */
```

**Comment by proh14** [comment]
so can you merge it i'll add the code now

**Comment by blueberry077** [comment]
thank you for you contribution !

**Comment by proh14** [comment]
np can you add the hacktoberfest-accepted label to this pr, Thank you

**Comment by blueberry077** [comment]
Is that it ?

**Comment by proh14** [comment]
yes thank you very much

**Pull request merged**
